backend:
  name: git-gateway
  branch: netlify-cms-test
publish_mode: editorial_workflow
media_folder: public/images
public_folder: images


collections:
  - label: Pages
    name: pages
    files:
      - includes: about.yml
      - label: Home
        name: home
        file: src/content/pages/home.md
        preview_path: content/pages/home
        fields:
          - { label: Logo, name: site-logo, widget: image }
          - { label: Background, name: home-bg, widget: image }
          - label: "Call To Action"
            name: home_call_to_action
            widget: object
            fields:
              - label: Lines
                name: hcta_lines
                widget: list
                fields:
                  - { label: Line, name: hcta_line, widget: string }
              - label: Buttons
                name: hcta_buttons
                widget: list
                fields:
                  - label: Button
                    name: hcta_button
                    widget: object
                    fields:
                      - { label: Text, name: hcta_button_text, widget: string }
                      - { label: Link, name: hcta_button_link, widget: string }
          - label: Newsletter
            name: home_news_letter
            widget: object
            fields:
              - { label: Title, name: hnl_title, widget: string }
              - { label: Placeholder, name: hnl_placeholder, widget: string }
              - { label: Text, name: hnl_button, widget: string }
          - label: Actions
            name: home_actions
            widget: list
            fields:
              - label: Action
                name: ha_action
                widget: object
                fields:
                  - { label: Text, name: ha_action_text, widget: string }
                  - { label: Image, name: ha_action_image, widget: image }
          - label: Links
            name: home_links
            widget: list
            fields:
              - label: Link
                name: hl_link
                widget: object
                fields:
                  - { label: Text, name: hl_link_text, widget: string }
                  - { label: Link, name: hl_link_nav, widget: string }
                  - { label: Image, name: hl_link_image, widget: image }